### ISSUE TITLE
Different result between Debug and Release

### ISSUE THREAD

**Issue by coooooooorey** [DuSTman31/SHA-3#3]
My Code：

<img width="698" alt="qq20170621-224605 2x" src="https://user-images.githubusercontent.com/3081374/27390536-1a1f5f3a-56d4-11e7-91b4-11264b0c5f15.png">

Input ”A“

Debug（Correct）：
421a35a60054e5f383b6137e43d44e998f496748cc77258240ccfaa8730b51f40cf47c1bc09c728a8cd4f096731298d51463f15af89543fed478053346260c38

Release：
fff33bdfffbfdbffb5712b45afaa596feaf59e440bf66b0f18948e4cc9ebc144e7c9f0a0aa3c8fc7375e2a4fc8add620f28210b2cb87f1d040448b62fbe7392a

**Comment by coooooooorey** [comment]
Hi~

I just found that it works fine on Windows, but it doesn't works fine on OSX.

**Comment by DuSTman31** [comment]
Hi. Looking into this now.
Does the unmodified code return the correct result with your compiler/settings on os x?

This might be an LLVM issue. I've tested with visual studio and gcc, but not llvm/clang

**Comment by coooooooorey** [comment]
I tried it with a new project, it's still the same.
: (

**Comment by coooooooorey** [comment]
Would you please help 😢

**Comment by DuSTman31** [comment]
Sure, I'll happily look into it.

Can you tell me what version the C++ compiler you're using on OSx is?

**Comment by DuSTman31** [comment]
Also, I notice you're using keccakdigest() instead of sha3Digest(). Sha3 is slightly different to standard keccak (slightly different padding rules), so these would generate different hashes?

**Comment by coooooooooorey** [comment]
Clang 7.0  64bit

**Comment by coooooooorey** [comment]
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin16.6.0
Thread model: posix

**Comment by coooooooorey** [comment]
I need the result from keccak_512, I thought using keccakdigest is the only way to get it?

**Comment by DuSTman31** [comment]
Yes, that's correct. But your method is named SHA3, which is different. Was just wondering if you intended that.

**Comment by DuSTman31** [comment]
I think I may have found the issue. Clang was behaving differently on my rotateLeft implementation. I've modified it so it works on my copy of clang. I've pushed a new version of rotation.h.

**Comment by coooooooorey** [comment]
Works now.

Thank you~~
