### ISSUE TITLE
Error when try execute program in Visual studio 2017

### ISSUE THREAD

**Issue by sergeyber** [DuSTman31/SHA-3#4]
'Keccak.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\kernel32.dll'
The thread 0x1184 has exited with code 0 (0x0).
The program '[8172] Keccak.exe' has exited with code 0 (0x0).

What version you use VS ?
Or how I can solve this problem ?

**Comment by DuSTman31** [comment]
Hi.. I use Visual Studio 2013 update 5.
If you're running from within visual studio with a debug build, it should tell you where the error is?

Thanks,
DH

**Comment by DuSTman31** [comment]
Have you ensured you've done a "clean solution" before building? This might just be due to some old files from the previous version..

**Comment by sergeyber** [comment]
Ok. After I aded file shorttest.txt I get SHA-3 hash.
Where I can use this parameters to change alhorithm ?
-a=s   :  Set algorithm to SHA-3 (default).
 -a=k   :  Set algotithm to Keccak.
 -a=h   :  Set algorithm to SHAKE

**Comment by DuSTman31** [comment]
In the solution explorer, right click on the project "keccak" and select properties. In the debugging tab, there's a "command arguments" field there. Just put the -a=k before the shortTest.txt, and that should do it..
