### ISSUE TITLE
sha3Digest

### ISSUE THREAD

**Issue by samrrr** [DuSTman31/SHA-3#5]
Its complete junk. 
1)state->length isnt a uint64_t count.
2)A is a 25 uint64
3)'for' really terrible

**Comment by DuSTman31** [comment]
Hi.
1: As state-length represents the hash width, it only needs to go up to 512, and doesn't need to be any particular size beyond that. Why use a 64 bit for this?
2: https://keccak.team/keccak_specs_summary.html states that "When implemented on a 64-bit processor, a lane of Keccak-f[1600] can be represented as a 64-bit CPU word." so I don't think there's anything wrong with using 64-bit types for the state array. 
3: If you're referring to keccakf, I deliberately unrolled this for speed. My test file (a 1Gb random file) completed in 23 seconds for the unrolled version, or 1 minute 15 for the original. It's ugly, but for a 3x speed increase, I'll take it.

**Comment by samrrr** [comment]
1,2)

char* argv1[] = {"1","-a=s", "-w=512","test.txt" };
parseCommandLine(4, argv1);

I am use this for test.
Im run on VS2017.

state->A = new uint64_t[25]; 
But in 'for' you access 0..63 its out of array.

uint64_t *tmp = new uint64_t[state->length];
Its allocates in memory 512*64 bits.
In for used only 512*8 bits.
Later used only 512 bits.
for(unsigned int i = 0 ; i != (hashSize/8) ; i++)
{
	printf("%.2x", *(op++));
}
And its memory newer delete.
Maybe use vector or shared ptr?

3)Its function used only once. This cant slow down 3x.

**Comment by DuSTman31** [comment]
Oh I see - I thought you were looking at something else. you're right. I've pushed what should be a fix for these issues.
Thanks,
DH
