### ISSUE TITLE
sha3Digest doesn't work for 224 because it is not a multiple of 64

### ISSUE THREAD

**Issue by jimschm** [DuSTman31/SHA-3#6]
The code looks like it computes the digest properly, but sha3Digest truncates the output to 24 bytes (192 bits), because math is 64-bit. The last 4 bytes are missing from the result.

**Comment by DuSTman31** [comment]
Good catch - this looks like it fixes it in my tests..

**Comment by jimschm** [comment]
Passes my tests also - good work
